# Generated by Django 3.1.4 on 2020-12-07 13:49

from django.db import migrations, models
import projects.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=255)),
                ('project_name', models.CharField(max_length=255)),
                ('project_address', models.CharField(max_length=255)),
                ('project_city', models.CharField(max_length=255)),
                ('project_state', models.CharField(max_length=2)),
                ('project_zip', projects.models.ZipCodeField()),
                ('project_start_date', models.DateField()),
                ('project_outstading_debt', models.DecimalField(blank=True, decimal_places=2, max_digits=20)),
                ('project_commencement_date', models.DateField(blank=True)),
            ],
            options={
                'verbose_name': 'Project',
            },
        ),
    ]
