# Generated by Django 3.1.4 on 2020-12-07 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='order_type',
            field=models.CharField(blank=True, choices=[('Notice', 'Notice'), ('Lien', 'Lien')], max_length=255),
        ),
    ]
