# Generated by Django 3.1.4 on 2020-12-07 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_projects_order_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='project_commencement_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='projects',
            name='project_start_date',
            field=models.DateField(auto_now=True),
        ),
    ]
