# Generated by Django 3.1.4 on 2020-12-07 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_auto_20201207_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='project_address',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
